package com.btjf.mapper.product;

import com.btjf.model.product.ProductProcedureWorkshop;
import com.btjf.model.product.ProductProcedureWorkshopExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductProcedureWorkshopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    long countByExample(ProductProcedureWorkshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    int deleteByExample(ProductProcedureWorkshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    int insert(ProductProcedureWorkshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    int insertSelective(ProductProcedureWorkshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    List<ProductProcedureWorkshop> selectByExample(ProductProcedureWorkshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    ProductProcedureWorkshop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductProcedureWorkshop record, @Param("example") ProductProcedureWorkshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductProcedureWorkshop record, @Param("example") ProductProcedureWorkshopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductProcedureWorkshop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_procedure_workshop
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductProcedureWorkshop record);

    Integer getNumByWorkShopNameAndPID(@Param("name") String name, @Param("productNo") String productNo);

    List<ProductProcedureWorkshop> findByWorkshopName(@Param("name") String name);

    List<ProductProcedureWorkshop> getWorkShop(@Param("productNo") String productNo);

    Integer deleteByProcedureId (@Param("procedureId") Integer procedureId);

    List<ProductProcedureWorkshop> getByWorkShopAndProductNo(@Param("workShop") String workShop, @Param("productNo") String productNo);

    List<ProductProcedureWorkshop> getBySort(@Param("integers") List<Integer> integers);
}