package com.btjf.model.emp;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Emp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.deptId
     *
     * @mbg.generated
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.isLeader
     *
     * @mbg.generated
     */
    private Integer isLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.workId
     *
     * @mbg.generated
     */
    private Integer workId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.nativeSource
     *
     * @mbg.generated
     */
    private String nativeSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.Nation
     *
     * @mbg.generated
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.idCard
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.entryDate
     *
     * @mbg.generated
     */
    private String entryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.education
     *
     * @mbg.generated
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.linkMan
     *
     * @mbg.generated
     */
    private String linkMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.salary
     *
     * @mbg.generated
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.ylbx
     *
     * @mbg.generated
     */
    private BigDecimal ylbx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.sybx
     *
     * @mbg.generated
     */
    private BigDecimal sybx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.yiliaobx
     *
     * @mbg.generated
     */
    private BigDecimal yiliaobx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.gjj
     *
     * @mbg.generated
     */
    private BigDecimal gjj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.dhbt
     *
     * @mbg.generated
     */
    private BigDecimal dhbt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.phoneSubsidy
     *
     * @mbg.generated
     */
    private BigDecimal phoneSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.waterSubsidy
     *
     * @mbg.generated
     */
    private BigDecimal waterSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.foodSubsidy
     *
     * @mbg.generated
     */
    private BigDecimal foodSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.socialSubsidy
     *
     * @mbg.generated
     */
    private BigDecimal socialSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Emp.isDelete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_Emp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.id
     *
     * @return the value of t_Emp.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.id
     *
     * @param id the value for t_Emp.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.name
     *
     * @return the value of t_Emp.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.name
     *
     * @param name the value for t_Emp.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.phone
     *
     * @return the value of t_Emp.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.phone
     *
     * @param phone the value for t_Emp.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.password
     *
     * @return the value of t_Emp.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.password
     *
     * @param password the value for t_Emp.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.deptId
     *
     * @return the value of t_Emp.deptId
     *
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.deptId
     *
     * @param deptId the value for t_Emp.deptId
     *
     * @mbg.generated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.isLeader
     *
     * @return the value of t_Emp.isLeader
     *
     * @mbg.generated
     */
    public Integer getIsLeader() {
        return isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.isLeader
     *
     * @param isLeader the value for t_Emp.isLeader
     *
     * @mbg.generated
     */
    public void setIsLeader(Integer isLeader) {
        this.isLeader = isLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.sex
     *
     * @return the value of t_Emp.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.sex
     *
     * @param sex the value for t_Emp.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.workId
     *
     * @return the value of t_Emp.workId
     *
     * @mbg.generated
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.workId
     *
     * @param workId the value for t_Emp.workId
     *
     * @mbg.generated
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.type
     *
     * @return the value of t_Emp.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.type
     *
     * @param type the value for t_Emp.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.nativeSource
     *
     * @return the value of t_Emp.nativeSource
     *
     * @mbg.generated
     */
    public String getNativeSource() {
        return nativeSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.nativeSource
     *
     * @param nativeSource the value for t_Emp.nativeSource
     *
     * @mbg.generated
     */
    public void setNativeSource(String nativeSource) {
        this.nativeSource = nativeSource == null ? null : nativeSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.Nation
     *
     * @return the value of t_Emp.Nation
     *
     * @mbg.generated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.Nation
     *
     * @param nation the value for t_Emp.Nation
     *
     * @mbg.generated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.birthday
     *
     * @return the value of t_Emp.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.birthday
     *
     * @param birthday the value for t_Emp.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.idCard
     *
     * @return the value of t_Emp.idCard
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.idCard
     *
     * @param idCard the value for t_Emp.idCard
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.entryDate
     *
     * @return the value of t_Emp.entryDate
     *
     * @mbg.generated
     */
    public String getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.entryDate
     *
     * @param entryDate the value for t_Emp.entryDate
     *
     * @mbg.generated
     */
    public void setEntryDate(String entryDate) {
        this.entryDate = entryDate == null ? null : entryDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.school
     *
     * @return the value of t_Emp.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.school
     *
     * @param school the value for t_Emp.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.subject
     *
     * @return the value of t_Emp.subject
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.subject
     *
     * @param subject the value for t_Emp.subject
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.education
     *
     * @return the value of t_Emp.education
     *
     * @mbg.generated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.education
     *
     * @param education the value for t_Emp.education
     *
     * @mbg.generated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.linkMan
     *
     * @return the value of t_Emp.linkMan
     *
     * @mbg.generated
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.linkMan
     *
     * @param linkMan the value for t_Emp.linkMan
     *
     * @mbg.generated
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.tel
     *
     * @return the value of t_Emp.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.tel
     *
     * @param tel the value for t_Emp.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.address
     *
     * @return the value of t_Emp.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.address
     *
     * @param address the value for t_Emp.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.salary
     *
     * @return the value of t_Emp.salary
     *
     * @mbg.generated
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.salary
     *
     * @param salary the value for t_Emp.salary
     *
     * @mbg.generated
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.ylbx
     *
     * @return the value of t_Emp.ylbx
     *
     * @mbg.generated
     */
    public BigDecimal getYlbx() {
        return ylbx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.ylbx
     *
     * @param ylbx the value for t_Emp.ylbx
     *
     * @mbg.generated
     */
    public void setYlbx(BigDecimal ylbx) {
        this.ylbx = ylbx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.sybx
     *
     * @return the value of t_Emp.sybx
     *
     * @mbg.generated
     */
    public BigDecimal getSybx() {
        return sybx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.sybx
     *
     * @param sybx the value for t_Emp.sybx
     *
     * @mbg.generated
     */
    public void setSybx(BigDecimal sybx) {
        this.sybx = sybx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.yiliaobx
     *
     * @return the value of t_Emp.yiliaobx
     *
     * @mbg.generated
     */
    public BigDecimal getYiliaobx() {
        return yiliaobx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.yiliaobx
     *
     * @param yiliaobx the value for t_Emp.yiliaobx
     *
     * @mbg.generated
     */
    public void setYiliaobx(BigDecimal yiliaobx) {
        this.yiliaobx = yiliaobx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.gjj
     *
     * @return the value of t_Emp.gjj
     *
     * @mbg.generated
     */
    public BigDecimal getGjj() {
        return gjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.gjj
     *
     * @param gjj the value for t_Emp.gjj
     *
     * @mbg.generated
     */
    public void setGjj(BigDecimal gjj) {
        this.gjj = gjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.dhbt
     *
     * @return the value of t_Emp.dhbt
     *
     * @mbg.generated
     */
    public BigDecimal getDhbt() {
        return dhbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.dhbt
     *
     * @param dhbt the value for t_Emp.dhbt
     *
     * @mbg.generated
     */
    public void setDhbt(BigDecimal dhbt) {
        this.dhbt = dhbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.phoneSubsidy
     *
     * @return the value of t_Emp.phoneSubsidy
     *
     * @mbg.generated
     */
    public BigDecimal getPhoneSubsidy() {
        return phoneSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.phoneSubsidy
     *
     * @param phoneSubsidy the value for t_Emp.phoneSubsidy
     *
     * @mbg.generated
     */
    public void setPhoneSubsidy(BigDecimal phoneSubsidy) {
        this.phoneSubsidy = phoneSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.waterSubsidy
     *
     * @return the value of t_Emp.waterSubsidy
     *
     * @mbg.generated
     */
    public BigDecimal getWaterSubsidy() {
        return waterSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.waterSubsidy
     *
     * @param waterSubsidy the value for t_Emp.waterSubsidy
     *
     * @mbg.generated
     */
    public void setWaterSubsidy(BigDecimal waterSubsidy) {
        this.waterSubsidy = waterSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.foodSubsidy
     *
     * @return the value of t_Emp.foodSubsidy
     *
     * @mbg.generated
     */
    public BigDecimal getFoodSubsidy() {
        return foodSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.foodSubsidy
     *
     * @param foodSubsidy the value for t_Emp.foodSubsidy
     *
     * @mbg.generated
     */
    public void setFoodSubsidy(BigDecimal foodSubsidy) {
        this.foodSubsidy = foodSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.socialSubsidy
     *
     * @return the value of t_Emp.socialSubsidy
     *
     * @mbg.generated
     */
    public BigDecimal getSocialSubsidy() {
        return socialSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.socialSubsidy
     *
     * @param socialSubsidy the value for t_Emp.socialSubsidy
     *
     * @mbg.generated
     */
    public void setSocialSubsidy(BigDecimal socialSubsidy) {
        this.socialSubsidy = socialSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.remark
     *
     * @return the value of t_Emp.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.remark
     *
     * @param remark the value for t_Emp.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.createTime
     *
     * @return the value of t_Emp.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.createTime
     *
     * @param createTime the value for t_Emp.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.lastModifyTime
     *
     * @return the value of t_Emp.lastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.lastModifyTime
     *
     * @param lastModifyTime the value for t_Emp.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Emp.isDelete
     *
     * @return the value of t_Emp.isDelete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Emp.isDelete
     *
     * @param isDelete the value for t_Emp.isDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Emp
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Emp other = (Emp) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getIsLeader() == null ? other.getIsLeader() == null : this.getIsLeader().equals(other.getIsLeader()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getWorkId() == null ? other.getWorkId() == null : this.getWorkId().equals(other.getWorkId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getNativeSource() == null ? other.getNativeSource() == null : this.getNativeSource().equals(other.getNativeSource()))
            && (this.getNation() == null ? other.getNation() == null : this.getNation().equals(other.getNation()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getIdCard() == null ? other.getIdCard() == null : this.getIdCard().equals(other.getIdCard()))
            && (this.getEntryDate() == null ? other.getEntryDate() == null : this.getEntryDate().equals(other.getEntryDate()))
            && (this.getSchool() == null ? other.getSchool() == null : this.getSchool().equals(other.getSchool()))
            && (this.getSubject() == null ? other.getSubject() == null : this.getSubject().equals(other.getSubject()))
            && (this.getEducation() == null ? other.getEducation() == null : this.getEducation().equals(other.getEducation()))
            && (this.getLinkMan() == null ? other.getLinkMan() == null : this.getLinkMan().equals(other.getLinkMan()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getSalary() == null ? other.getSalary() == null : this.getSalary().equals(other.getSalary()))
            && (this.getYlbx() == null ? other.getYlbx() == null : this.getYlbx().equals(other.getYlbx()))
            && (this.getSybx() == null ? other.getSybx() == null : this.getSybx().equals(other.getSybx()))
            && (this.getYiliaobx() == null ? other.getYiliaobx() == null : this.getYiliaobx().equals(other.getYiliaobx()))
            && (this.getGjj() == null ? other.getGjj() == null : this.getGjj().equals(other.getGjj()))
            && (this.getDhbt() == null ? other.getDhbt() == null : this.getDhbt().equals(other.getDhbt()))
            && (this.getPhoneSubsidy() == null ? other.getPhoneSubsidy() == null : this.getPhoneSubsidy().equals(other.getPhoneSubsidy()))
            && (this.getWaterSubsidy() == null ? other.getWaterSubsidy() == null : this.getWaterSubsidy().equals(other.getWaterSubsidy()))
            && (this.getFoodSubsidy() == null ? other.getFoodSubsidy() == null : this.getFoodSubsidy().equals(other.getFoodSubsidy()))
            && (this.getSocialSubsidy() == null ? other.getSocialSubsidy() == null : this.getSocialSubsidy().equals(other.getSocialSubsidy()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Emp
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getIsLeader() == null) ? 0 : getIsLeader().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getWorkId() == null) ? 0 : getWorkId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getNativeSource() == null) ? 0 : getNativeSource().hashCode());
        result = prime * result + ((getNation() == null) ? 0 : getNation().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getIdCard() == null) ? 0 : getIdCard().hashCode());
        result = prime * result + ((getEntryDate() == null) ? 0 : getEntryDate().hashCode());
        result = prime * result + ((getSchool() == null) ? 0 : getSchool().hashCode());
        result = prime * result + ((getSubject() == null) ? 0 : getSubject().hashCode());
        result = prime * result + ((getEducation() == null) ? 0 : getEducation().hashCode());
        result = prime * result + ((getLinkMan() == null) ? 0 : getLinkMan().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getSalary() == null) ? 0 : getSalary().hashCode());
        result = prime * result + ((getYlbx() == null) ? 0 : getYlbx().hashCode());
        result = prime * result + ((getSybx() == null) ? 0 : getSybx().hashCode());
        result = prime * result + ((getYiliaobx() == null) ? 0 : getYiliaobx().hashCode());
        result = prime * result + ((getGjj() == null) ? 0 : getGjj().hashCode());
        result = prime * result + ((getDhbt() == null) ? 0 : getDhbt().hashCode());
        result = prime * result + ((getPhoneSubsidy() == null) ? 0 : getPhoneSubsidy().hashCode());
        result = prime * result + ((getWaterSubsidy() == null) ? 0 : getWaterSubsidy().hashCode());
        result = prime * result + ((getFoodSubsidy() == null) ? 0 : getFoodSubsidy().hashCode());
        result = prime * result + ((getSocialSubsidy() == null) ? 0 : getSocialSubsidy().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}