package com.btjf.model.emp;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SummarySalaryMonthly implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.yearMonth
     *
     * @mbg.generated
     */
    private String yearMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.empId
     *
     * @mbg.generated
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.empName
     *
     * @mbg.generated
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.deptId
     *
     * @mbg.generated
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.deptName
     *
     * @mbg.generated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.workName
     *
     * @mbg.generated
     */
    private String workName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.dayWork
     *
     * @mbg.generated
     */
    private BigDecimal dayWork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.nightWork
     *
     * @mbg.generated
     */
    private BigDecimal nightWork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.score
     *
     * @mbg.generated
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.sumWorkHour
     *
     * @mbg.generated
     */
    private BigDecimal sumWorkHour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.hourSalary
     *
     * @mbg.generated
     */
    private BigDecimal hourSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.restDay
     *
     * @mbg.generated
     */
    private BigDecimal restDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.sumDay
     *
     * @mbg.generated
     */
    private BigDecimal sumDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.daySalary
     *
     * @mbg.generated
     */
    private BigDecimal daySalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.dhbt
     *
     * @mbg.generated
     */
    private BigDecimal dhbt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.timeSalary
     *
     * @mbg.generated
     */
    private BigDecimal timeSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.nigthSnack
     *
     * @mbg.generated
     */
    private BigDecimal nigthSnack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.phoneSubsidy
     *
     * @mbg.generated
     */
    private BigDecimal phoneSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.mealSubsidy
     *
     * @mbg.generated
     */
    private BigDecimal mealSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.socialSubsidy
     *
     * @mbg.generated
     */
    private BigDecimal socialSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.hourSubsidy
     *
     * @mbg.generated
     */
    private BigDecimal hourSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.otherSubsidy
     *
     * @mbg.generated
     */
    private BigDecimal otherSubsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.sumSusbsidy
     *
     * @mbg.generated
     */
    private BigDecimal sumSusbsidy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.realSalary
     *
     * @mbg.generated
     */
    private BigDecimal realSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.ylbx
     *
     * @mbg.generated
     */
    private BigDecimal ylbx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.sybx
     *
     * @mbg.generated
     */
    private BigDecimal sybx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.yiliaobx
     *
     * @mbg.generated
     */
    private BigDecimal yiliaobx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.gjj
     *
     * @mbg.generated
     */
    private BigDecimal gjj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.otherDeduction
     *
     * @mbg.generated
     */
    private BigDecimal otherDeduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.sumDeduction
     *
     * @mbg.generated
     */
    private BigDecimal sumDeduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.trueSalary
     *
     * @mbg.generated
     */
    private BigDecimal trueSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.normalOvertime
     *
     * @mbg.generated
     */
    private BigDecimal normalOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.holiayOvertime
     *
     * @mbg.generated
     */
    private BigDecimal holiayOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.legalOvertime
     *
     * @mbg.generated
     */
    private BigDecimal legalOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_summary_salary_monthly.isDelete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.id
     *
     * @return the value of t_summary_salary_monthly.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.id
     *
     * @param id the value for t_summary_salary_monthly.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.yearMonth
     *
     * @return the value of t_summary_salary_monthly.yearMonth
     *
     * @mbg.generated
     */
    public String getYearMonth() {
        return yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.yearMonth
     *
     * @param yearMonth the value for t_summary_salary_monthly.yearMonth
     *
     * @mbg.generated
     */
    public void setYearMonth(String yearMonth) {
        this.yearMonth = yearMonth == null ? null : yearMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.empId
     *
     * @return the value of t_summary_salary_monthly.empId
     *
     * @mbg.generated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.empId
     *
     * @param empId the value for t_summary_salary_monthly.empId
     *
     * @mbg.generated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.empName
     *
     * @return the value of t_summary_salary_monthly.empName
     *
     * @mbg.generated
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.empName
     *
     * @param empName the value for t_summary_salary_monthly.empName
     *
     * @mbg.generated
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.deptId
     *
     * @return the value of t_summary_salary_monthly.deptId
     *
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.deptId
     *
     * @param deptId the value for t_summary_salary_monthly.deptId
     *
     * @mbg.generated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.deptName
     *
     * @return the value of t_summary_salary_monthly.deptName
     *
     * @mbg.generated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.deptName
     *
     * @param deptName the value for t_summary_salary_monthly.deptName
     *
     * @mbg.generated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.workName
     *
     * @return the value of t_summary_salary_monthly.workName
     *
     * @mbg.generated
     */
    public String getWorkName() {
        return workName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.workName
     *
     * @param workName the value for t_summary_salary_monthly.workName
     *
     * @mbg.generated
     */
    public void setWorkName(String workName) {
        this.workName = workName == null ? null : workName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.dayWork
     *
     * @return the value of t_summary_salary_monthly.dayWork
     *
     * @mbg.generated
     */
    public BigDecimal getDayWork() {
        return dayWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.dayWork
     *
     * @param dayWork the value for t_summary_salary_monthly.dayWork
     *
     * @mbg.generated
     */
    public void setDayWork(BigDecimal dayWork) {
        this.dayWork = dayWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.nightWork
     *
     * @return the value of t_summary_salary_monthly.nightWork
     *
     * @mbg.generated
     */
    public BigDecimal getNightWork() {
        return nightWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.nightWork
     *
     * @param nightWork the value for t_summary_salary_monthly.nightWork
     *
     * @mbg.generated
     */
    public void setNightWork(BigDecimal nightWork) {
        this.nightWork = nightWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.score
     *
     * @return the value of t_summary_salary_monthly.score
     *
     * @mbg.generated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.score
     *
     * @param score the value for t_summary_salary_monthly.score
     *
     * @mbg.generated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.sumWorkHour
     *
     * @return the value of t_summary_salary_monthly.sumWorkHour
     *
     * @mbg.generated
     */
    public BigDecimal getSumWorkHour() {
        return sumWorkHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.sumWorkHour
     *
     * @param sumWorkHour the value for t_summary_salary_monthly.sumWorkHour
     *
     * @mbg.generated
     */
    public void setSumWorkHour(BigDecimal sumWorkHour) {
        this.sumWorkHour = sumWorkHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.hourSalary
     *
     * @return the value of t_summary_salary_monthly.hourSalary
     *
     * @mbg.generated
     */
    public BigDecimal getHourSalary() {
        return hourSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.hourSalary
     *
     * @param hourSalary the value for t_summary_salary_monthly.hourSalary
     *
     * @mbg.generated
     */
    public void setHourSalary(BigDecimal hourSalary) {
        this.hourSalary = hourSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.restDay
     *
     * @return the value of t_summary_salary_monthly.restDay
     *
     * @mbg.generated
     */
    public BigDecimal getRestDay() {
        return restDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.restDay
     *
     * @param restDay the value for t_summary_salary_monthly.restDay
     *
     * @mbg.generated
     */
    public void setRestDay(BigDecimal restDay) {
        this.restDay = restDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.sumDay
     *
     * @return the value of t_summary_salary_monthly.sumDay
     *
     * @mbg.generated
     */
    public BigDecimal getSumDay() {
        return sumDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.sumDay
     *
     * @param sumDay the value for t_summary_salary_monthly.sumDay
     *
     * @mbg.generated
     */
    public void setSumDay(BigDecimal sumDay) {
        this.sumDay = sumDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.daySalary
     *
     * @return the value of t_summary_salary_monthly.daySalary
     *
     * @mbg.generated
     */
    public BigDecimal getDaySalary() {
        return daySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.daySalary
     *
     * @param daySalary the value for t_summary_salary_monthly.daySalary
     *
     * @mbg.generated
     */
    public void setDaySalary(BigDecimal daySalary) {
        this.daySalary = daySalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.dhbt
     *
     * @return the value of t_summary_salary_monthly.dhbt
     *
     * @mbg.generated
     */
    public BigDecimal getDhbt() {
        return dhbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.dhbt
     *
     * @param dhbt the value for t_summary_salary_monthly.dhbt
     *
     * @mbg.generated
     */
    public void setDhbt(BigDecimal dhbt) {
        this.dhbt = dhbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.type
     *
     * @return the value of t_summary_salary_monthly.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.type
     *
     * @param type the value for t_summary_salary_monthly.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.timeSalary
     *
     * @return the value of t_summary_salary_monthly.timeSalary
     *
     * @mbg.generated
     */
    public BigDecimal getTimeSalary() {
        return timeSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.timeSalary
     *
     * @param timeSalary the value for t_summary_salary_monthly.timeSalary
     *
     * @mbg.generated
     */
    public void setTimeSalary(BigDecimal timeSalary) {
        this.timeSalary = timeSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.nigthSnack
     *
     * @return the value of t_summary_salary_monthly.nigthSnack
     *
     * @mbg.generated
     */
    public BigDecimal getNigthSnack() {
        return nigthSnack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.nigthSnack
     *
     * @param nigthSnack the value for t_summary_salary_monthly.nigthSnack
     *
     * @mbg.generated
     */
    public void setNigthSnack(BigDecimal nigthSnack) {
        this.nigthSnack = nigthSnack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.phoneSubsidy
     *
     * @return the value of t_summary_salary_monthly.phoneSubsidy
     *
     * @mbg.generated
     */
    public BigDecimal getPhoneSubsidy() {
        return phoneSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.phoneSubsidy
     *
     * @param phoneSubsidy the value for t_summary_salary_monthly.phoneSubsidy
     *
     * @mbg.generated
     */
    public void setPhoneSubsidy(BigDecimal phoneSubsidy) {
        this.phoneSubsidy = phoneSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.mealSubsidy
     *
     * @return the value of t_summary_salary_monthly.mealSubsidy
     *
     * @mbg.generated
     */
    public BigDecimal getMealSubsidy() {
        return mealSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.mealSubsidy
     *
     * @param mealSubsidy the value for t_summary_salary_monthly.mealSubsidy
     *
     * @mbg.generated
     */
    public void setMealSubsidy(BigDecimal mealSubsidy) {
        this.mealSubsidy = mealSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.socialSubsidy
     *
     * @return the value of t_summary_salary_monthly.socialSubsidy
     *
     * @mbg.generated
     */
    public BigDecimal getSocialSubsidy() {
        return socialSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.socialSubsidy
     *
     * @param socialSubsidy the value for t_summary_salary_monthly.socialSubsidy
     *
     * @mbg.generated
     */
    public void setSocialSubsidy(BigDecimal socialSubsidy) {
        this.socialSubsidy = socialSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.hourSubsidy
     *
     * @return the value of t_summary_salary_monthly.hourSubsidy
     *
     * @mbg.generated
     */
    public BigDecimal getHourSubsidy() {
        return hourSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.hourSubsidy
     *
     * @param hourSubsidy the value for t_summary_salary_monthly.hourSubsidy
     *
     * @mbg.generated
     */
    public void setHourSubsidy(BigDecimal hourSubsidy) {
        this.hourSubsidy = hourSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.otherSubsidy
     *
     * @return the value of t_summary_salary_monthly.otherSubsidy
     *
     * @mbg.generated
     */
    public BigDecimal getOtherSubsidy() {
        return otherSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.otherSubsidy
     *
     * @param otherSubsidy the value for t_summary_salary_monthly.otherSubsidy
     *
     * @mbg.generated
     */
    public void setOtherSubsidy(BigDecimal otherSubsidy) {
        this.otherSubsidy = otherSubsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.sumSusbsidy
     *
     * @return the value of t_summary_salary_monthly.sumSusbsidy
     *
     * @mbg.generated
     */
    public BigDecimal getSumSusbsidy() {
        return sumSusbsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.sumSusbsidy
     *
     * @param sumSusbsidy the value for t_summary_salary_monthly.sumSusbsidy
     *
     * @mbg.generated
     */
    public void setSumSusbsidy(BigDecimal sumSusbsidy) {
        this.sumSusbsidy = sumSusbsidy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.realSalary
     *
     * @return the value of t_summary_salary_monthly.realSalary
     *
     * @mbg.generated
     */
    public BigDecimal getRealSalary() {
        return realSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.realSalary
     *
     * @param realSalary the value for t_summary_salary_monthly.realSalary
     *
     * @mbg.generated
     */
    public void setRealSalary(BigDecimal realSalary) {
        this.realSalary = realSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.ylbx
     *
     * @return the value of t_summary_salary_monthly.ylbx
     *
     * @mbg.generated
     */
    public BigDecimal getYlbx() {
        return ylbx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.ylbx
     *
     * @param ylbx the value for t_summary_salary_monthly.ylbx
     *
     * @mbg.generated
     */
    public void setYlbx(BigDecimal ylbx) {
        this.ylbx = ylbx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.sybx
     *
     * @return the value of t_summary_salary_monthly.sybx
     *
     * @mbg.generated
     */
    public BigDecimal getSybx() {
        return sybx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.sybx
     *
     * @param sybx the value for t_summary_salary_monthly.sybx
     *
     * @mbg.generated
     */
    public void setSybx(BigDecimal sybx) {
        this.sybx = sybx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.yiliaobx
     *
     * @return the value of t_summary_salary_monthly.yiliaobx
     *
     * @mbg.generated
     */
    public BigDecimal getYiliaobx() {
        return yiliaobx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.yiliaobx
     *
     * @param yiliaobx the value for t_summary_salary_monthly.yiliaobx
     *
     * @mbg.generated
     */
    public void setYiliaobx(BigDecimal yiliaobx) {
        this.yiliaobx = yiliaobx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.gjj
     *
     * @return the value of t_summary_salary_monthly.gjj
     *
     * @mbg.generated
     */
    public BigDecimal getGjj() {
        return gjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.gjj
     *
     * @param gjj the value for t_summary_salary_monthly.gjj
     *
     * @mbg.generated
     */
    public void setGjj(BigDecimal gjj) {
        this.gjj = gjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.otherDeduction
     *
     * @return the value of t_summary_salary_monthly.otherDeduction
     *
     * @mbg.generated
     */
    public BigDecimal getOtherDeduction() {
        return otherDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.otherDeduction
     *
     * @param otherDeduction the value for t_summary_salary_monthly.otherDeduction
     *
     * @mbg.generated
     */
    public void setOtherDeduction(BigDecimal otherDeduction) {
        this.otherDeduction = otherDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.sumDeduction
     *
     * @return the value of t_summary_salary_monthly.sumDeduction
     *
     * @mbg.generated
     */
    public BigDecimal getSumDeduction() {
        return sumDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.sumDeduction
     *
     * @param sumDeduction the value for t_summary_salary_monthly.sumDeduction
     *
     * @mbg.generated
     */
    public void setSumDeduction(BigDecimal sumDeduction) {
        this.sumDeduction = sumDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.trueSalary
     *
     * @return the value of t_summary_salary_monthly.trueSalary
     *
     * @mbg.generated
     */
    public BigDecimal getTrueSalary() {
        return trueSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.trueSalary
     *
     * @param trueSalary the value for t_summary_salary_monthly.trueSalary
     *
     * @mbg.generated
     */
    public void setTrueSalary(BigDecimal trueSalary) {
        this.trueSalary = trueSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.normalOvertime
     *
     * @return the value of t_summary_salary_monthly.normalOvertime
     *
     * @mbg.generated
     */
    public BigDecimal getNormalOvertime() {
        return normalOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.normalOvertime
     *
     * @param normalOvertime the value for t_summary_salary_monthly.normalOvertime
     *
     * @mbg.generated
     */
    public void setNormalOvertime(BigDecimal normalOvertime) {
        this.normalOvertime = normalOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.holiayOvertime
     *
     * @return the value of t_summary_salary_monthly.holiayOvertime
     *
     * @mbg.generated
     */
    public BigDecimal getHoliayOvertime() {
        return holiayOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.holiayOvertime
     *
     * @param holiayOvertime the value for t_summary_salary_monthly.holiayOvertime
     *
     * @mbg.generated
     */
    public void setHoliayOvertime(BigDecimal holiayOvertime) {
        this.holiayOvertime = holiayOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.legalOvertime
     *
     * @return the value of t_summary_salary_monthly.legalOvertime
     *
     * @mbg.generated
     */
    public BigDecimal getLegalOvertime() {
        return legalOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.legalOvertime
     *
     * @param legalOvertime the value for t_summary_salary_monthly.legalOvertime
     *
     * @mbg.generated
     */
    public void setLegalOvertime(BigDecimal legalOvertime) {
        this.legalOvertime = legalOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.createTime
     *
     * @return the value of t_summary_salary_monthly.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.createTime
     *
     * @param createTime the value for t_summary_salary_monthly.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.lastModifyTime
     *
     * @return the value of t_summary_salary_monthly.lastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.lastModifyTime
     *
     * @param lastModifyTime the value for t_summary_salary_monthly.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_summary_salary_monthly.isDelete
     *
     * @return the value of t_summary_salary_monthly.isDelete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_summary_salary_monthly.isDelete
     *
     * @param isDelete the value for t_summary_salary_monthly.isDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SummarySalaryMonthly other = (SummarySalaryMonthly) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getYearMonth() == null ? other.getYearMonth() == null : this.getYearMonth().equals(other.getYearMonth()))
            && (this.getEmpId() == null ? other.getEmpId() == null : this.getEmpId().equals(other.getEmpId()))
            && (this.getEmpName() == null ? other.getEmpName() == null : this.getEmpName().equals(other.getEmpName()))
            && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
            && (this.getDeptName() == null ? other.getDeptName() == null : this.getDeptName().equals(other.getDeptName()))
            && (this.getWorkName() == null ? other.getWorkName() == null : this.getWorkName().equals(other.getWorkName()))
            && (this.getDayWork() == null ? other.getDayWork() == null : this.getDayWork().equals(other.getDayWork()))
            && (this.getNightWork() == null ? other.getNightWork() == null : this.getNightWork().equals(other.getNightWork()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getSumWorkHour() == null ? other.getSumWorkHour() == null : this.getSumWorkHour().equals(other.getSumWorkHour()))
            && (this.getHourSalary() == null ? other.getHourSalary() == null : this.getHourSalary().equals(other.getHourSalary()))
            && (this.getRestDay() == null ? other.getRestDay() == null : this.getRestDay().equals(other.getRestDay()))
            && (this.getSumDay() == null ? other.getSumDay() == null : this.getSumDay().equals(other.getSumDay()))
            && (this.getDaySalary() == null ? other.getDaySalary() == null : this.getDaySalary().equals(other.getDaySalary()))
            && (this.getDhbt() == null ? other.getDhbt() == null : this.getDhbt().equals(other.getDhbt()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getTimeSalary() == null ? other.getTimeSalary() == null : this.getTimeSalary().equals(other.getTimeSalary()))
            && (this.getNigthSnack() == null ? other.getNigthSnack() == null : this.getNigthSnack().equals(other.getNigthSnack()))
            && (this.getPhoneSubsidy() == null ? other.getPhoneSubsidy() == null : this.getPhoneSubsidy().equals(other.getPhoneSubsidy()))
            && (this.getMealSubsidy() == null ? other.getMealSubsidy() == null : this.getMealSubsidy().equals(other.getMealSubsidy()))
            && (this.getSocialSubsidy() == null ? other.getSocialSubsidy() == null : this.getSocialSubsidy().equals(other.getSocialSubsidy()))
            && (this.getHourSubsidy() == null ? other.getHourSubsidy() == null : this.getHourSubsidy().equals(other.getHourSubsidy()))
            && (this.getOtherSubsidy() == null ? other.getOtherSubsidy() == null : this.getOtherSubsidy().equals(other.getOtherSubsidy()))
            && (this.getSumSusbsidy() == null ? other.getSumSusbsidy() == null : this.getSumSusbsidy().equals(other.getSumSusbsidy()))
            && (this.getRealSalary() == null ? other.getRealSalary() == null : this.getRealSalary().equals(other.getRealSalary()))
            && (this.getYlbx() == null ? other.getYlbx() == null : this.getYlbx().equals(other.getYlbx()))
            && (this.getSybx() == null ? other.getSybx() == null : this.getSybx().equals(other.getSybx()))
            && (this.getYiliaobx() == null ? other.getYiliaobx() == null : this.getYiliaobx().equals(other.getYiliaobx()))
            && (this.getGjj() == null ? other.getGjj() == null : this.getGjj().equals(other.getGjj()))
            && (this.getOtherDeduction() == null ? other.getOtherDeduction() == null : this.getOtherDeduction().equals(other.getOtherDeduction()))
            && (this.getSumDeduction() == null ? other.getSumDeduction() == null : this.getSumDeduction().equals(other.getSumDeduction()))
            && (this.getTrueSalary() == null ? other.getTrueSalary() == null : this.getTrueSalary().equals(other.getTrueSalary()))
            && (this.getNormalOvertime() == null ? other.getNormalOvertime() == null : this.getNormalOvertime().equals(other.getNormalOvertime()))
            && (this.getHoliayOvertime() == null ? other.getHoliayOvertime() == null : this.getHoliayOvertime().equals(other.getHoliayOvertime()))
            && (this.getLegalOvertime() == null ? other.getLegalOvertime() == null : this.getLegalOvertime().equals(other.getLegalOvertime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getYearMonth() == null) ? 0 : getYearMonth().hashCode());
        result = prime * result + ((getEmpId() == null) ? 0 : getEmpId().hashCode());
        result = prime * result + ((getEmpName() == null) ? 0 : getEmpName().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getDeptName() == null) ? 0 : getDeptName().hashCode());
        result = prime * result + ((getWorkName() == null) ? 0 : getWorkName().hashCode());
        result = prime * result + ((getDayWork() == null) ? 0 : getDayWork().hashCode());
        result = prime * result + ((getNightWork() == null) ? 0 : getNightWork().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getSumWorkHour() == null) ? 0 : getSumWorkHour().hashCode());
        result = prime * result + ((getHourSalary() == null) ? 0 : getHourSalary().hashCode());
        result = prime * result + ((getRestDay() == null) ? 0 : getRestDay().hashCode());
        result = prime * result + ((getSumDay() == null) ? 0 : getSumDay().hashCode());
        result = prime * result + ((getDaySalary() == null) ? 0 : getDaySalary().hashCode());
        result = prime * result + ((getDhbt() == null) ? 0 : getDhbt().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getTimeSalary() == null) ? 0 : getTimeSalary().hashCode());
        result = prime * result + ((getNigthSnack() == null) ? 0 : getNigthSnack().hashCode());
        result = prime * result + ((getPhoneSubsidy() == null) ? 0 : getPhoneSubsidy().hashCode());
        result = prime * result + ((getMealSubsidy() == null) ? 0 : getMealSubsidy().hashCode());
        result = prime * result + ((getSocialSubsidy() == null) ? 0 : getSocialSubsidy().hashCode());
        result = prime * result + ((getHourSubsidy() == null) ? 0 : getHourSubsidy().hashCode());
        result = prime * result + ((getOtherSubsidy() == null) ? 0 : getOtherSubsidy().hashCode());
        result = prime * result + ((getSumSusbsidy() == null) ? 0 : getSumSusbsidy().hashCode());
        result = prime * result + ((getRealSalary() == null) ? 0 : getRealSalary().hashCode());
        result = prime * result + ((getYlbx() == null) ? 0 : getYlbx().hashCode());
        result = prime * result + ((getSybx() == null) ? 0 : getSybx().hashCode());
        result = prime * result + ((getYiliaobx() == null) ? 0 : getYiliaobx().hashCode());
        result = prime * result + ((getGjj() == null) ? 0 : getGjj().hashCode());
        result = prime * result + ((getOtherDeduction() == null) ? 0 : getOtherDeduction().hashCode());
        result = prime * result + ((getSumDeduction() == null) ? 0 : getSumDeduction().hashCode());
        result = prime * result + ((getTrueSalary() == null) ? 0 : getTrueSalary().hashCode());
        result = prime * result + ((getNormalOvertime() == null) ? 0 : getNormalOvertime().hashCode());
        result = prime * result + ((getHoliayOvertime() == null) ? 0 : getHoliayOvertime().hashCode());
        result = prime * result + ((getLegalOvertime() == null) ? 0 : getLegalOvertime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}