package com.btjf.mapper.emp;

import com.btjf.controller.emp.vo.EmpSubsibyMonthlyVo;
import com.btjf.model.emp.EmpSubsibyMonthly;
import com.btjf.model.emp.EmpSubsibyMonthlyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmpSubsibyMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    long countByExample(EmpSubsibyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    int deleteByExample(EmpSubsibyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    int insert(EmpSubsibyMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    int insertSelective(EmpSubsibyMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    List<EmpSubsibyMonthly> selectByExample(EmpSubsibyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    EmpSubsibyMonthly selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmpSubsibyMonthly record, @Param("example") EmpSubsibyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmpSubsibyMonthly record, @Param("example") EmpSubsibyMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmpSubsibyMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_subsidy_monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmpSubsibyMonthly record);

    public EmpSubsibyMonthly getByNo(@Param("billNo") String billNo, @Param("type") Integer type);

    public List<EmpSubsibyMonthlyVo> list(@Param("yearMonth") String yearMonth, @Param("empName") String empName,
                                   @Param("billNo") String billNo, @Param("deptName") String deptName,
                                   @Param("isConfirm") Integer isConfirm, @Param("type") Integer type);

    public Integer confirm(@Param("ids") List<String> ids);


    public Double getSumSubsiby(@Param("yearMonth") String yearMonth, @Param("empId") Integer empId, @Param("type") Integer type);
}