package com.btjf.mapper.emp;

import com.btjf.model.emp.EmpSalaryMonthly;
import com.btjf.model.emp.EmpSalaryMonthlyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmpSalaryMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    long countByExample(EmpSalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    int deleteByExample(EmpSalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    int insert(EmpSalaryMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    int insertSelective(EmpSalaryMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    List<EmpSalaryMonthly> selectByExample(EmpSalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    EmpSalaryMonthly selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmpSalaryMonthly record, @Param("example") EmpSalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmpSalaryMonthly record, @Param("example") EmpSalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmpSalaryMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_salary_monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmpSalaryMonthly record);

    Integer deleteByYearMonthAndName(@Param("yearMonth") String yearMonth, @Param("name") String empName);

    List<EmpSalaryMonthly> getList(@Param("yearMonth") String yearMonth, @Param("empName") String empName, @Param("deptName") String deptName, @Param("type") Integer type);

    List<String> getYearMonth();

    EmpSalaryMonthly getByYearMonthAndName(@Param("yearMonth") String yearMonth, @Param("name") String name);
}