package com.btjf.mapper.emp;

import com.btjf.model.emp.empTimesalaryMonthly;
import com.btjf.model.emp.empTimesalaryMonthlyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface empTimesalaryMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    long countByExample(empTimesalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    int deleteByExample(empTimesalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    int insert(empTimesalaryMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    int insertSelective(empTimesalaryMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    List<empTimesalaryMonthly> selectByExample(empTimesalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    empTimesalaryMonthly selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") empTimesalaryMonthly record, @Param("example") empTimesalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") empTimesalaryMonthly record, @Param("example") empTimesalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(empTimesalaryMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_timesalary_monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(empTimesalaryMonthly record);
}