package com.btjf.mapper.emp;

import com.btjf.model.emp.Empwork;
import com.btjf.model.emp.EmpworkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    long countByExample(EmpworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    int deleteByExample(EmpworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    int insert(Empwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    int insertSelective(Empwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    List<Empwork> selectByExample(EmpworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    Empwork selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Empwork record, @Param("example") EmpworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Empwork record, @Param("example") EmpworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Empwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp_work
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Empwork record);
}