package com.btjf.mapper.emp;

import com.btjf.model.emp.SummarySalaryMonthly;
import com.btjf.model.emp.SummarySalaryMonthlyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SummarySalaryMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    long countByExample(SummarySalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    int deleteByExample(SummarySalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    int insert(SummarySalaryMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    int insertSelective(SummarySalaryMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    List<SummarySalaryMonthly> selectByExample(SummarySalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    SummarySalaryMonthly selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SummarySalaryMonthly record, @Param("example") SummarySalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SummarySalaryMonthly record, @Param("example") SummarySalaryMonthlyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SummarySalaryMonthly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_summary_salary_monthly
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SummarySalaryMonthly record);

    SummarySalaryMonthly getByEmpIDAndYearMonth(@Param("empId") Integer empId, @Param("yearMonth") String yearMonth);
}