package com.btjf.model.pm;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PmIn implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.pmId
     *
     * @mbg.generated
     */
    private Integer pmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.pmNo
     *
     * @mbg.generated
     */
    private String pmNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.pmName
     *
     * @mbg.generated
     */
    private String pmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.supplier
     *
     * @mbg.generated
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.inDate
     *
     * @mbg.generated
     */
    private Date inDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.num
     *
     * @mbg.generated
     */
    private BigDecimal num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.perNum
     *
     * @mbg.generated
     */
    private BigDecimal perNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.backNum
     *
     * @mbg.generated
     */
    private BigDecimal backNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_PMIn.isDelete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.id
     *
     * @return the value of t_PMIn.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.id
     *
     * @param id the value for t_PMIn.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.pmId
     *
     * @return the value of t_PMIn.pmId
     *
     * @mbg.generated
     */
    public Integer getPmId() {
        return pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.pmId
     *
     * @param pmId the value for t_PMIn.pmId
     *
     * @mbg.generated
     */
    public void setPmId(Integer pmId) {
        this.pmId = pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.pmNo
     *
     * @return the value of t_PMIn.pmNo
     *
     * @mbg.generated
     */
    public String getPmNo() {
        return pmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.pmNo
     *
     * @param pmNo the value for t_PMIn.pmNo
     *
     * @mbg.generated
     */
    public void setPmNo(String pmNo) {
        this.pmNo = pmNo == null ? null : pmNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.pmName
     *
     * @return the value of t_PMIn.pmName
     *
     * @mbg.generated
     */
    public String getPmName() {
        return pmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.pmName
     *
     * @param pmName the value for t_PMIn.pmName
     *
     * @mbg.generated
     */
    public void setPmName(String pmName) {
        this.pmName = pmName == null ? null : pmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.type
     *
     * @return the value of t_PMIn.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.type
     *
     * @param type the value for t_PMIn.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.unit
     *
     * @return the value of t_PMIn.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.unit
     *
     * @param unit the value for t_PMIn.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.remark
     *
     * @return the value of t_PMIn.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.remark
     *
     * @param remark the value for t_PMIn.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.supplier
     *
     * @return the value of t_PMIn.supplier
     *
     * @mbg.generated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.supplier
     *
     * @param supplier the value for t_PMIn.supplier
     *
     * @mbg.generated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.inDate
     *
     * @return the value of t_PMIn.inDate
     *
     * @mbg.generated
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.inDate
     *
     * @param inDate the value for t_PMIn.inDate
     *
     * @mbg.generated
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.num
     *
     * @return the value of t_PMIn.num
     *
     * @mbg.generated
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.num
     *
     * @param num the value for t_PMIn.num
     *
     * @mbg.generated
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.perNum
     *
     * @return the value of t_PMIn.perNum
     *
     * @mbg.generated
     */
    public BigDecimal getPerNum() {
        return perNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.perNum
     *
     * @param perNum the value for t_PMIn.perNum
     *
     * @mbg.generated
     */
    public void setPerNum(BigDecimal perNum) {
        this.perNum = perNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.backNum
     *
     * @return the value of t_PMIn.backNum
     *
     * @mbg.generated
     */
    public BigDecimal getBackNum() {
        return backNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.backNum
     *
     * @param backNum the value for t_PMIn.backNum
     *
     * @mbg.generated
     */
    public void setBackNum(BigDecimal backNum) {
        this.backNum = backNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.operator
     *
     * @return the value of t_PMIn.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.operator
     *
     * @param operator the value for t_PMIn.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.createTime
     *
     * @return the value of t_PMIn.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.createTime
     *
     * @param createTime the value for t_PMIn.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.lastModifyTime
     *
     * @return the value of t_PMIn.lastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.lastModifyTime
     *
     * @param lastModifyTime the value for t_PMIn.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_PMIn.isDelete
     *
     * @return the value of t_PMIn.isDelete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_PMIn.isDelete
     *
     * @param isDelete the value for t_PMIn.isDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmIn other = (PmIn) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPmId() == null ? other.getPmId() == null : this.getPmId().equals(other.getPmId()))
            && (this.getPmNo() == null ? other.getPmNo() == null : this.getPmNo().equals(other.getPmNo()))
            && (this.getPmName() == null ? other.getPmName() == null : this.getPmName().equals(other.getPmName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getSupplier() == null ? other.getSupplier() == null : this.getSupplier().equals(other.getSupplier()))
            && (this.getInDate() == null ? other.getInDate() == null : this.getInDate().equals(other.getInDate()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getPerNum() == null ? other.getPerNum() == null : this.getPerNum().equals(other.getPerNum()))
            && (this.getBackNum() == null ? other.getBackNum() == null : this.getBackNum().equals(other.getBackNum()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_PMIn
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPmId() == null) ? 0 : getPmId().hashCode());
        result = prime * result + ((getPmNo() == null) ? 0 : getPmNo().hashCode());
        result = prime * result + ((getPmName() == null) ? 0 : getPmName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getSupplier() == null) ? 0 : getSupplier().hashCode());
        result = prime * result + ((getInDate() == null) ? 0 : getInDate().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getPerNum() == null) ? 0 : getPerNum().hashCode());
        result = prime * result + ((getBackNum() == null) ? 0 : getBackNum().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}