package com.btjf.model.pm;

import java.io.Serializable;
import java.util.Date;

public class PmoutBillDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.billId
     *
     * @mbg.generated
     */
    private Integer billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.pmId
     *
     * @mbg.generated
     */
    private Integer pmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.pmNo
     *
     * @mbg.generated
     */
    private String pmNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.pmName
     *
     * @mbg.generated
     */
    private String pmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.pmBatchNo
     *
     * @mbg.generated
     */
    private String pmBatchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.perNum
     *
     * @mbg.generated
     */
    private Integer perNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.backNum
     *
     * @mbg.generated
     */
    private Integer backNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.outInfo
     *
     * @mbg.generated
     */
    private String outInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.receiver
     *
     * @mbg.generated
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.sender
     *
     * @mbg.generated
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill_detail.isDelete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pmout_bill_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.id
     *
     * @return the value of t_pmout_bill_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.id
     *
     * @param id the value for t_pmout_bill_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.billId
     *
     * @return the value of t_pmout_bill_detail.billId
     *
     * @mbg.generated
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.billId
     *
     * @param billId the value for t_pmout_bill_detail.billId
     *
     * @mbg.generated
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.pmId
     *
     * @return the value of t_pmout_bill_detail.pmId
     *
     * @mbg.generated
     */
    public Integer getPmId() {
        return pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.pmId
     *
     * @param pmId the value for t_pmout_bill_detail.pmId
     *
     * @mbg.generated
     */
    public void setPmId(Integer pmId) {
        this.pmId = pmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.pmNo
     *
     * @return the value of t_pmout_bill_detail.pmNo
     *
     * @mbg.generated
     */
    public String getPmNo() {
        return pmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.pmNo
     *
     * @param pmNo the value for t_pmout_bill_detail.pmNo
     *
     * @mbg.generated
     */
    public void setPmNo(String pmNo) {
        this.pmNo = pmNo == null ? null : pmNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.pmName
     *
     * @return the value of t_pmout_bill_detail.pmName
     *
     * @mbg.generated
     */
    public String getPmName() {
        return pmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.pmName
     *
     * @param pmName the value for t_pmout_bill_detail.pmName
     *
     * @mbg.generated
     */
    public void setPmName(String pmName) {
        this.pmName = pmName == null ? null : pmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.pmBatchNo
     *
     * @return the value of t_pmout_bill_detail.pmBatchNo
     *
     * @mbg.generated
     */
    public String getPmBatchNo() {
        return pmBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.pmBatchNo
     *
     * @param pmBatchNo the value for t_pmout_bill_detail.pmBatchNo
     *
     * @mbg.generated
     */
    public void setPmBatchNo(String pmBatchNo) {
        this.pmBatchNo = pmBatchNo == null ? null : pmBatchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.num
     *
     * @return the value of t_pmout_bill_detail.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.num
     *
     * @param num the value for t_pmout_bill_detail.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.perNum
     *
     * @return the value of t_pmout_bill_detail.perNum
     *
     * @mbg.generated
     */
    public Integer getPerNum() {
        return perNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.perNum
     *
     * @param perNum the value for t_pmout_bill_detail.perNum
     *
     * @mbg.generated
     */
    public void setPerNum(Integer perNum) {
        this.perNum = perNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.backNum
     *
     * @return the value of t_pmout_bill_detail.backNum
     *
     * @mbg.generated
     */
    public Integer getBackNum() {
        return backNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.backNum
     *
     * @param backNum the value for t_pmout_bill_detail.backNum
     *
     * @mbg.generated
     */
    public void setBackNum(Integer backNum) {
        this.backNum = backNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.unit
     *
     * @return the value of t_pmout_bill_detail.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.unit
     *
     * @param unit the value for t_pmout_bill_detail.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.remark
     *
     * @return the value of t_pmout_bill_detail.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.remark
     *
     * @param remark the value for t_pmout_bill_detail.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.outInfo
     *
     * @return the value of t_pmout_bill_detail.outInfo
     *
     * @mbg.generated
     */
    public String getOutInfo() {
        return outInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.outInfo
     *
     * @param outInfo the value for t_pmout_bill_detail.outInfo
     *
     * @mbg.generated
     */
    public void setOutInfo(String outInfo) {
        this.outInfo = outInfo == null ? null : outInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.receiver
     *
     * @return the value of t_pmout_bill_detail.receiver
     *
     * @mbg.generated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.receiver
     *
     * @param receiver the value for t_pmout_bill_detail.receiver
     *
     * @mbg.generated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.sender
     *
     * @return the value of t_pmout_bill_detail.sender
     *
     * @mbg.generated
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.sender
     *
     * @param sender the value for t_pmout_bill_detail.sender
     *
     * @mbg.generated
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.operator
     *
     * @return the value of t_pmout_bill_detail.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.operator
     *
     * @param operator the value for t_pmout_bill_detail.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.createTime
     *
     * @return the value of t_pmout_bill_detail.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.createTime
     *
     * @param createTime the value for t_pmout_bill_detail.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.lastModifyTime
     *
     * @return the value of t_pmout_bill_detail.lastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.lastModifyTime
     *
     * @param lastModifyTime the value for t_pmout_bill_detail.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill_detail.isDelete
     *
     * @return the value of t_pmout_bill_detail.isDelete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill_detail.isDelete
     *
     * @param isDelete the value for t_pmout_bill_detail.isDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pmout_bill_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmoutBillDetail other = (PmoutBillDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBillId() == null ? other.getBillId() == null : this.getBillId().equals(other.getBillId()))
            && (this.getPmId() == null ? other.getPmId() == null : this.getPmId().equals(other.getPmId()))
            && (this.getPmNo() == null ? other.getPmNo() == null : this.getPmNo().equals(other.getPmNo()))
            && (this.getPmName() == null ? other.getPmName() == null : this.getPmName().equals(other.getPmName()))
            && (this.getPmBatchNo() == null ? other.getPmBatchNo() == null : this.getPmBatchNo().equals(other.getPmBatchNo()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
            && (this.getPerNum() == null ? other.getPerNum() == null : this.getPerNum().equals(other.getPerNum()))
            && (this.getBackNum() == null ? other.getBackNum() == null : this.getBackNum().equals(other.getBackNum()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getOutInfo() == null ? other.getOutInfo() == null : this.getOutInfo().equals(other.getOutInfo()))
            && (this.getReceiver() == null ? other.getReceiver() == null : this.getReceiver().equals(other.getReceiver()))
            && (this.getSender() == null ? other.getSender() == null : this.getSender().equals(other.getSender()))
            && (this.getOperator() == null ? other.getOperator() == null : this.getOperator().equals(other.getOperator()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pmout_bill_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBillId() == null) ? 0 : getBillId().hashCode());
        result = prime * result + ((getPmId() == null) ? 0 : getPmId().hashCode());
        result = prime * result + ((getPmNo() == null) ? 0 : getPmNo().hashCode());
        result = prime * result + ((getPmName() == null) ? 0 : getPmName().hashCode());
        result = prime * result + ((getPmBatchNo() == null) ? 0 : getPmBatchNo().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getPerNum() == null) ? 0 : getPerNum().hashCode());
        result = prime * result + ((getBackNum() == null) ? 0 : getBackNum().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getOutInfo() == null) ? 0 : getOutInfo().hashCode());
        result = prime * result + ((getReceiver() == null) ? 0 : getReceiver().hashCode());
        result = prime * result + ((getSender() == null) ? 0 : getSender().hashCode());
        result = prime * result + ((getOperator() == null) ? 0 : getOperator().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}