package com.btjf.model.pm;

import java.io.Serializable;
import java.util.Date;

public class PmOutBill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.orderId
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.orderNo
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.productId
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.productNo
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.billNo
     *
     * @mbg.generated
     */
    private String billNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.workshop
     *
     * @mbg.generated
     */
    private Integer workshop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.distributionNum
     *
     * @mbg.generated
     */
    private Integer distributionNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.groupNmae
     *
     * @mbg.generated
     */
    private String groupNmae;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.leader
     *
     * @mbg.generated
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.pmType
     *
     * @mbg.generated
     */
    private String pmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.pmCheckItem
     *
     * @mbg.generated
     */
    private String pmCheckItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pmout_bill.isDelete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pmout_bill
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.id
     *
     * @return the value of t_pmout_bill.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.id
     *
     * @param id the value for t_pmout_bill.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.orderId
     *
     * @return the value of t_pmout_bill.orderId
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.orderId
     *
     * @param orderId the value for t_pmout_bill.orderId
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.orderNo
     *
     * @return the value of t_pmout_bill.orderNo
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.orderNo
     *
     * @param orderNo the value for t_pmout_bill.orderNo
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.productId
     *
     * @return the value of t_pmout_bill.productId
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.productId
     *
     * @param productId the value for t_pmout_bill.productId
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.productNo
     *
     * @return the value of t_pmout_bill.productNo
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.productNo
     *
     * @param productNo the value for t_pmout_bill.productNo
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.billNo
     *
     * @return the value of t_pmout_bill.billNo
     *
     * @mbg.generated
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.billNo
     *
     * @param billNo the value for t_pmout_bill.billNo
     *
     * @mbg.generated
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.type
     *
     * @return the value of t_pmout_bill.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.type
     *
     * @param type the value for t_pmout_bill.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.workshop
     *
     * @return the value of t_pmout_bill.workshop
     *
     * @mbg.generated
     */
    public Integer getWorkshop() {
        return workshop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.workshop
     *
     * @param workshop the value for t_pmout_bill.workshop
     *
     * @mbg.generated
     */
    public void setWorkshop(Integer workshop) {
        this.workshop = workshop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.distributionNum
     *
     * @return the value of t_pmout_bill.distributionNum
     *
     * @mbg.generated
     */
    public Integer getDistributionNum() {
        return distributionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.distributionNum
     *
     * @param distributionNum the value for t_pmout_bill.distributionNum
     *
     * @mbg.generated
     */
    public void setDistributionNum(Integer distributionNum) {
        this.distributionNum = distributionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.groupNmae
     *
     * @return the value of t_pmout_bill.groupNmae
     *
     * @mbg.generated
     */
    public String getGroupNmae() {
        return groupNmae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.groupNmae
     *
     * @param groupNmae the value for t_pmout_bill.groupNmae
     *
     * @mbg.generated
     */
    public void setGroupNmae(String groupNmae) {
        this.groupNmae = groupNmae == null ? null : groupNmae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.leader
     *
     * @return the value of t_pmout_bill.leader
     *
     * @mbg.generated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.leader
     *
     * @param leader the value for t_pmout_bill.leader
     *
     * @mbg.generated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.pmType
     *
     * @return the value of t_pmout_bill.pmType
     *
     * @mbg.generated
     */
    public String getPmType() {
        return pmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.pmType
     *
     * @param pmType the value for t_pmout_bill.pmType
     *
     * @mbg.generated
     */
    public void setPmType(String pmType) {
        this.pmType = pmType == null ? null : pmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.pmCheckItem
     *
     * @return the value of t_pmout_bill.pmCheckItem
     *
     * @mbg.generated
     */
    public String getPmCheckItem() {
        return pmCheckItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.pmCheckItem
     *
     * @param pmCheckItem the value for t_pmout_bill.pmCheckItem
     *
     * @mbg.generated
     */
    public void setPmCheckItem(String pmCheckItem) {
        this.pmCheckItem = pmCheckItem == null ? null : pmCheckItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.createTime
     *
     * @return the value of t_pmout_bill.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.createTime
     *
     * @param createTime the value for t_pmout_bill.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.lastModifyTime
     *
     * @return the value of t_pmout_bill.lastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.lastModifyTime
     *
     * @param lastModifyTime the value for t_pmout_bill.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pmout_bill.isDelete
     *
     * @return the value of t_pmout_bill.isDelete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pmout_bill.isDelete
     *
     * @param isDelete the value for t_pmout_bill.isDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pmout_bill
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmOutBill other = (PmOutBill) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getProductNo() == null ? other.getProductNo() == null : this.getProductNo().equals(other.getProductNo()))
            && (this.getBillNo() == null ? other.getBillNo() == null : this.getBillNo().equals(other.getBillNo()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getWorkshop() == null ? other.getWorkshop() == null : this.getWorkshop().equals(other.getWorkshop()))
            && (this.getDistributionNum() == null ? other.getDistributionNum() == null : this.getDistributionNum().equals(other.getDistributionNum()))
            && (this.getGroupNmae() == null ? other.getGroupNmae() == null : this.getGroupNmae().equals(other.getGroupNmae()))
            && (this.getLeader() == null ? other.getLeader() == null : this.getLeader().equals(other.getLeader()))
            && (this.getPmType() == null ? other.getPmType() == null : this.getPmType().equals(other.getPmType()))
            && (this.getPmCheckItem() == null ? other.getPmCheckItem() == null : this.getPmCheckItem().equals(other.getPmCheckItem()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pmout_bill
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getProductNo() == null) ? 0 : getProductNo().hashCode());
        result = prime * result + ((getBillNo() == null) ? 0 : getBillNo().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getWorkshop() == null) ? 0 : getWorkshop().hashCode());
        result = prime * result + ((getDistributionNum() == null) ? 0 : getDistributionNum().hashCode());
        result = prime * result + ((getGroupNmae() == null) ? 0 : getGroupNmae().hashCode());
        result = prime * result + ((getLeader() == null) ? 0 : getLeader().hashCode());
        result = prime * result + ((getPmType() == null) ? 0 : getPmType().hashCode());
        result = prime * result + ((getPmCheckItem() == null) ? 0 : getPmCheckItem().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}