package com.btjf.model.order;

import java.io.Serializable;
import java.util.Date;

public class OrderProduct implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.orderId
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.orderNo
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.productId
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.productNo
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.productType
     *
     * @mbg.generated
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.maxNum
     *
     * @mbg.generated
     */
    private Integer maxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.completeDate
     *
     * @mbg.generated
     */
    private Date completeDate;

    private String completeDateStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.customerId
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.customerName
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.isMore
     *
     * @mbg.generated
     */
    private Integer isMore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.urgentLevel
     *
     * @mbg.generated
     */
    private Integer urgentLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.leader
     *
     * @mbg.generated
     */
    private String leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.pmType
     *
     * @mbg.generated
     */
    private String pmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.pmCheckItem
     *
     * @mbg.generated
     */
    private String pmCheckItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.isDelete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.assignedNum
     *
     * @mbg.generated
     */
    private Integer assignedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product.notAssignNum
     *
     * @mbg.generated
     */
    private Integer notAssignNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public OrderProduct() {
    }

    public OrderProduct(Integer orderId, String orderNo, Integer productId, String productNo, String productType, Integer num, Integer maxNum, String unit, Date completeDate, Integer customerId, String customerName, Integer isMore, Integer urgentLevel, String leader, String pmType, String pmCheckItem, Date createTime, Date lastModifyTime, Integer isDelete) {
        this.orderId = orderId;
        this.orderNo = orderNo;
        this.productId = productId;
        this.productNo = productNo;
        this.productType = productType;
        this.num = num;
        this.maxNum = maxNum;
        this.unit = unit;
        this.completeDate = completeDate;
        this.customerId = customerId;
        this.customerName = customerName;
        this.isMore = isMore;
        this.urgentLevel = urgentLevel;
        this.leader = leader;
        this.pmType = pmType;
        this.pmCheckItem = pmCheckItem;
        this.createTime = createTime;
        this.lastModifyTime = lastModifyTime;
        this.isDelete = isDelete;
    }

    public OrderProduct(Integer id, Integer orderId, String orderNo, Integer productId, String productNo, String productType, Integer num, Integer maxNum, String unit, Date completeDate, Integer customerId, String customerName, Integer isMore, Integer urgentLevel, String leader, String pmType, String pmCheckItem, Date createTime, Date lastModifyTime, Integer isDelete, Integer assignedNum, Integer notAssignNum) {
        this.id = id;
        this.orderId = orderId;
        this.orderNo = orderNo;
        this.productId = productId;
        this.productNo = productNo;
        this.productType = productType;
        this.num = num;
        this.maxNum = maxNum;
        this.unit = unit;
        this.completeDate = completeDate;
        this.customerId = customerId;
        this.customerName = customerName;
        this.isMore = isMore;
        this.urgentLevel = urgentLevel;
        this.leader = leader;
        this.pmType = pmType;
        this.pmCheckItem = pmCheckItem;
        this.createTime = createTime;
        this.lastModifyTime = lastModifyTime;
        this.isDelete = isDelete;
        this.assignedNum = assignedNum;
        this.notAssignNum = notAssignNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.id
     *
     * @return the value of t_order_product.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.id
     *
     * @param id the value for t_order_product.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.orderId
     *
     * @return the value of t_order_product.orderId
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    public String getCompleteDateStr() {
        return completeDateStr;
    }

    public void setCompleteDateStr(String completeDateStr) {
        this.completeDateStr = completeDateStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.orderId
     *
     * @param orderId the value for t_order_product.orderId
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.orderNo
     *
     * @return the value of t_order_product.orderNo
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.orderNo
     *
     * @param orderNo the value for t_order_product.orderNo
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.productId
     *
     * @return the value of t_order_product.productId
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.productId
     *
     * @param productId the value for t_order_product.productId
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.productNo
     *
     * @return the value of t_order_product.productNo
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.productNo
     *
     * @param productNo the value for t_order_product.productNo
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.productType
     *
     * @return the value of t_order_product.productType
     * @mbg.generated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.productType
     *
     * @param productType the value for t_order_product.productType
     * @mbg.generated
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.num
     *
     * @return the value of t_order_product.num
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.num
     *
     * @param num the value for t_order_product.num
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.maxNum
     *
     * @return the value of t_order_product.maxNum
     * @mbg.generated
     */
    public Integer getMaxNum() {
        return maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.maxNum
     *
     * @param maxNum the value for t_order_product.maxNum
     * @mbg.generated
     */
    public void setMaxNum(Integer maxNum) {
        this.maxNum = maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.unit
     *
     * @return the value of t_order_product.unit
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.unit
     *
     * @param unit the value for t_order_product.unit
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.completeDate
     *
     * @return the value of t_order_product.completeDate
     * @mbg.generated
     */
    public Date getCompleteDate() {
        return completeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.completeDate
     *
     * @param completeDate the value for t_order_product.completeDate
     * @mbg.generated
     */
    public void setCompleteDate(Date completeDate) {
        this.completeDate = completeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.customerId
     *
     * @return the value of t_order_product.customerId
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.customerId
     *
     * @param customerId the value for t_order_product.customerId
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.customerName
     *
     * @return the value of t_order_product.customerName
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.customerName
     *
     * @param customerName the value for t_order_product.customerName
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.isMore
     *
     * @return the value of t_order_product.isMore
     * @mbg.generated
     */
    public Integer getIsMore() {
        return isMore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.isMore
     *
     * @param isMore the value for t_order_product.isMore
     * @mbg.generated
     */
    public void setIsMore(Integer isMore) {
        this.isMore = isMore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.urgentLevel
     *
     * @return the value of t_order_product.urgentLevel
     * @mbg.generated
     */
    public Integer getUrgentLevel() {
        return urgentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.urgentLevel
     *
     * @param urgentLevel the value for t_order_product.urgentLevel
     * @mbg.generated
     */
    public void setUrgentLevel(Integer urgentLevel) {
        this.urgentLevel = urgentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.leader
     *
     * @return the value of t_order_product.leader
     * @mbg.generated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.leader
     *
     * @param leader the value for t_order_product.leader
     * @mbg.generated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.pmType
     *
     * @return the value of t_order_product.pmType
     * @mbg.generated
     */
    public String getPmType() {
        return pmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.pmType
     *
     * @param pmType the value for t_order_product.pmType
     * @mbg.generated
     */
    public void setPmType(String pmType) {
        this.pmType = pmType == null ? null : pmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.pmCheckItem
     *
     * @return the value of t_order_product.pmCheckItem
     * @mbg.generated
     */
    public String getPmCheckItem() {
        return pmCheckItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.pmCheckItem
     *
     * @param pmCheckItem the value for t_order_product.pmCheckItem
     * @mbg.generated
     */
    public void setPmCheckItem(String pmCheckItem) {
        this.pmCheckItem = pmCheckItem == null ? null : pmCheckItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.createTime
     *
     * @return the value of t_order_product.createTime
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.createTime
     *
     * @param createTime the value for t_order_product.createTime
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.lastModifyTime
     *
     * @return the value of t_order_product.lastModifyTime
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.lastModifyTime
     *
     * @param lastModifyTime the value for t_order_product.lastModifyTime
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.isDelete
     *
     * @return the value of t_order_product.isDelete
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.isDelete
     *
     * @param isDelete the value for t_order_product.isDelete
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.assignedNum
     *
     * @return the value of t_order_product.assignedNum
     * @mbg.generated
     */
    public Integer getAssignedNum() {
        return assignedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.assignedNum
     *
     * @param assignedNum the value for t_order_product.assignedNum
     * @mbg.generated
     */
    public void setAssignedNum(Integer assignedNum) {
        this.assignedNum = assignedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product.notAssignNum
     *
     * @return the value of t_order_product.notAssignNum
     * @mbg.generated
     */
    public Integer getNotAssignNum() {
        return notAssignNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product.notAssignNum
     *
     * @param notAssignNum the value for t_order_product.notAssignNum
     * @mbg.generated
     */
    public void setNotAssignNum(Integer notAssignNum) {
        this.notAssignNum = notAssignNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderProduct other = (OrderProduct) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
                && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
                && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
                && (this.getProductNo() == null ? other.getProductNo() == null : this.getProductNo().equals(other.getProductNo()))
                && (this.getProductType() == null ? other.getProductType() == null : this.getProductType().equals(other.getProductType()))
                && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()))
                && (this.getMaxNum() == null ? other.getMaxNum() == null : this.getMaxNum().equals(other.getMaxNum()))
                && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
                && (this.getCompleteDate() == null ? other.getCompleteDate() == null : this.getCompleteDate().equals(other.getCompleteDate()))
                && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
                && (this.getCustomerName() == null ? other.getCustomerName() == null : this.getCustomerName().equals(other.getCustomerName()))
                && (this.getIsMore() == null ? other.getIsMore() == null : this.getIsMore().equals(other.getIsMore()))
                && (this.getUrgentLevel() == null ? other.getUrgentLevel() == null : this.getUrgentLevel().equals(other.getUrgentLevel()))
                && (this.getLeader() == null ? other.getLeader() == null : this.getLeader().equals(other.getLeader()))
                && (this.getPmType() == null ? other.getPmType() == null : this.getPmType().equals(other.getPmType()))
                && (this.getPmCheckItem() == null ? other.getPmCheckItem() == null : this.getPmCheckItem().equals(other.getPmCheckItem()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
                && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
                && (this.getAssignedNum() == null ? other.getAssignedNum() == null : this.getAssignedNum().equals(other.getAssignedNum()))
                && (this.getNotAssignNum() == null ? other.getNotAssignNum() == null : this.getNotAssignNum().equals(other.getNotAssignNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getProductNo() == null) ? 0 : getProductNo().hashCode());
        result = prime * result + ((getProductType() == null) ? 0 : getProductType().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        result = prime * result + ((getMaxNum() == null) ? 0 : getMaxNum().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getCompleteDate() == null) ? 0 : getCompleteDate().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getCustomerName() == null) ? 0 : getCustomerName().hashCode());
        result = prime * result + ((getIsMore() == null) ? 0 : getIsMore().hashCode());
        result = prime * result + ((getUrgentLevel() == null) ? 0 : getUrgentLevel().hashCode());
        result = prime * result + ((getLeader() == null) ? 0 : getLeader().hashCode());
        result = prime * result + ((getPmType() == null) ? 0 : getPmType().hashCode());
        result = prime * result + ((getPmCheckItem() == null) ? 0 : getPmCheckItem().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getAssignedNum() == null) ? 0 : getAssignedNum().hashCode());
        result = prime * result + ((getNotAssignNum() == null) ? 0 : getNotAssignNum().hashCode());
        return result;
    }
}