package com.btjf.model.Order;

import java.io.Serializable;
import java.util.Date;

public class OrderProductWorkshop implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product_workshop.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product_workshop.orderProductId
     *
     * @mbg.generated
     */
    private Integer orderProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product_workshop.workshop
     *
     * @mbg.generated
     */
    private String workshop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product_workshop.leader
     *
     * @mbg.generated
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product_workshop.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product_workshop.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_product_workshop.isDelete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_product_workshop
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product_workshop.id
     *
     * @return the value of t_order_product_workshop.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product_workshop.id
     *
     * @param id the value for t_order_product_workshop.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product_workshop.orderProductId
     *
     * @return the value of t_order_product_workshop.orderProductId
     *
     * @mbg.generated
     */
    public Integer getOrderProductId() {
        return orderProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product_workshop.orderProductId
     *
     * @param orderProductId the value for t_order_product_workshop.orderProductId
     *
     * @mbg.generated
     */
    public void setOrderProductId(Integer orderProductId) {
        this.orderProductId = orderProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product_workshop.workshop
     *
     * @return the value of t_order_product_workshop.workshop
     *
     * @mbg.generated
     */
    public String getWorkshop() {
        return workshop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product_workshop.workshop
     *
     * @param workshop the value for t_order_product_workshop.workshop
     *
     * @mbg.generated
     */
    public void setWorkshop(String workshop) {
        this.workshop = workshop == null ? null : workshop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product_workshop.leader
     *
     * @return the value of t_order_product_workshop.leader
     *
     * @mbg.generated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product_workshop.leader
     *
     * @param leader the value for t_order_product_workshop.leader
     *
     * @mbg.generated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product_workshop.createTime
     *
     * @return the value of t_order_product_workshop.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product_workshop.createTime
     *
     * @param createTime the value for t_order_product_workshop.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product_workshop.lastModifyTime
     *
     * @return the value of t_order_product_workshop.lastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product_workshop.lastModifyTime
     *
     * @param lastModifyTime the value for t_order_product_workshop.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_product_workshop.isDelete
     *
     * @return the value of t_order_product_workshop.isDelete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_product_workshop.isDelete
     *
     * @param isDelete the value for t_order_product_workshop.isDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product_workshop
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderProductWorkshop other = (OrderProductWorkshop) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderProductId() == null ? other.getOrderProductId() == null : this.getOrderProductId().equals(other.getOrderProductId()))
            && (this.getWorkshop() == null ? other.getWorkshop() == null : this.getWorkshop().equals(other.getWorkshop()))
            && (this.getLeader() == null ? other.getLeader() == null : this.getLeader().equals(other.getLeader()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLastModifyTime() == null ? other.getLastModifyTime() == null : this.getLastModifyTime().equals(other.getLastModifyTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_product_workshop
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderProductId() == null) ? 0 : getOrderProductId().hashCode());
        result = prime * result + ((getWorkshop() == null) ? 0 : getWorkshop().hashCode());
        result = prime * result + ((getLeader() == null) ? 0 : getLeader().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLastModifyTime() == null) ? 0 : getLastModifyTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }
}