package com.btjf.mapper.order;

import com.btjf.model.order.ProductionProcedureConfirm;
import com.btjf.model.order.ProductionProcedureConfirmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionProcedureConfirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    long countByExample(ProductionProcedureConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    int deleteByExample(ProductionProcedureConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    int insert(ProductionProcedureConfirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    int insertSelective(ProductionProcedureConfirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    List<ProductionProcedureConfirm> selectByExample(ProductionProcedureConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    ProductionProcedureConfirm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductionProcedureConfirm record, @Param("example") ProductionProcedureConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductionProcedureConfirm record, @Param("example") ProductionProcedureConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductionProcedureConfirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_confirm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductionProcedureConfirm record);
}