package com.btjf.mapper.order;

import com.btjf.model.order.ProductionProcedure;
import com.btjf.model.order.ProductionProcedureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionProcedureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    long countByExample(ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    int deleteByExample(ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    int insert(ProductionProcedure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    int insertSelective(ProductionProcedure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    List<ProductionProcedure> selectByExample(ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    ProductionProcedure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductionProcedure record, @Param("example") ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductionProcedure record, @Param("example") ProductionProcedureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductionProcedure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductionProcedure record);

    List<ProductionProcedure> findByProductionNo(@Param("productionNo") String productionNo);

    List<ProductionProcedure> getConfigProcedure(@Param("deptName") String deptName, @Param("productionNo") String productionNo);

    Integer deleteByProductionNo(@Param("productionNo") String productionNo);

    Integer procedureCanAssignNum(@Param("orderNo") String orderNo, @Param("productNo") String productNo, @Param("procedureId") Integer procedureId);
}