package com.btjf.mapper.order;

import com.btjf.controller.order.vo.OrderVo;
import com.btjf.model.order.ProductionProcedureScan;
import com.btjf.model.order.ProductionProcedureScanExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.annotation.Resource;
import java.util.List;

public interface ProductionProcedureScanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    long countByExample(ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int deleteByExample(ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int insert(ProductionProcedureScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int insertSelective(ProductionProcedureScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    List<ProductionProcedureScan> selectByExample(ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    ProductionProcedureScan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductionProcedureScan record, @Param("example") ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductionProcedureScan record, @Param("example") ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductionProcedureScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductionProcedureScan record);

    Integer delete(@Param("orderNo") String orderNo,
                   @Param("productNo") String productNo, @Param("productionNo") String productionNo,
                   @Param("louId") Integer louId,@Param("billOutNo") String billOutNo, @Param("procedureId") Integer procedureId);

    List<ProductionProcedureScan> select(@Param("orderNo") String orderNo,
                   @Param("productNo") String productNo, @Param("productionNo") String productionNo,
                   @Param("louId") Integer louId,@Param("billOutNo") String billOutNo, @Param("procedureId") Integer procedureId);

    Integer updateSatue(@Param("id") Integer id, @Param("status") Integer status);

    ProductionProcedureScan selectLastMonth(ProductionProcedureScan convert);

    Integer getHandleNum(@Param("orderNo") String orderNo, @Param("procedureName") String procedureName, @Param("productNo") String productNo);

    List<OrderVo.ProcessDetail> getByProcduct(@Param("ids") List<Integer> ids, @Param("orderNo") String orderNo, @Param("product") String product);
}