package com.btjf.mapper.order;

import com.btjf.model.order.ProductionProcedureScan;
import com.btjf.model.order.ProductionProcedureScanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionProcedureScanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    long countByExample(ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int deleteByExample(ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int insert(ProductionProcedureScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int insertSelective(ProductionProcedureScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    List<ProductionProcedureScan> selectByExample(ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    ProductionProcedureScan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductionProcedureScan record, @Param("example") ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductionProcedureScan record, @Param("example") ProductionProcedureScanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductionProcedureScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_production_procedure_scan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductionProcedureScan record);
}