package com.btjf.mapper.order;

import com.btjf.controller.productionorder.vo.ProductionOrderVo;
import com.btjf.model.order.ProductionOrder;
import com.btjf.model.order.ProductionOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    long countByExample(ProductionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    int deleteByExample(ProductionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    int insert(ProductionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    int insertSelective(ProductionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    List<ProductionOrder> selectByExample(ProductionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    ProductionOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductionOrder record, @Param("example") ProductionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductionOrder record, @Param("example") ProductionOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Production_Order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductionOrder record);

    ProductionOrder getByOrderProductID(@Param("orderProductID") Integer orderProductID);

    List<ProductionOrderVo> findList(ProductionOrderVo productionOrderVo);

    ProductionOrder getByNo(@Param("productionNo") String productionNo);
}